"""Ajout champ banner_url à Event

Revision ID: 4b119a3f7b37
Revises: 675460a91d38
Create Date: 2025-04-11 00:16:47.477443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b119a3f7b37'
down_revision: Union[str, None] = '675460a91d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'banner_url')
    # ### end Alembic commands ###
