"""Ajout messagerie (conversations, messages, participants)

Revision ID: 54bc67682d73
Revises: 9853db6b637a
Create Date: 2025-04-10 16:26:05.838057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bc67682d73'
down_revision: Union[str, None] = '9853db6b637a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
