"""initial clean migration

Revision ID: 5d61f5ac30ad
Revises: e9f0f3c8a688
Create Date: 2025-04-11 01:19:19.890792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d61f5ac30ad'
down_revision: Union[str, None] = 'e9f0f3c8a688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
