"""Ajout champ banner_url à Event

Revision ID: e9f0f3c8a688
Revises: 5c67f52e5391
Create Date: 2025-04-11 00:24:15.654580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f0f3c8a688'
down_revision: Union[str, None] = '5c67f52e5391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
